New. SFW. CustomDB implemented.
CleanTalk/php-uni pull request #15
Opened 2023-08-28 16:37 UTC by svfcode

2023-08-29 09:50 UTC, Glomberg requested changes

2023-08-29 09:50 UTC, Glomberg commented on cleantalk/fw_nets_meta.php
> +  'rows' => 13350,
The `rows` must be 0 in the repository.

2023-08-29 09:50 UTC, Glomberg commented on cleantalk/lib/Cleantalk/ApbctUni/File/BTree.php
> +						// $myfile = fopen(__DIR__ . "/btree-get-a.txt", "a") or die("Unable to open file!");
Debug?

2023-08-29 13:44 UTC, svfcode commented on cleantalk/fw_nets_meta.php
> +  'rows' => 13350,
Fixed.

2023-08-29 13:44 UTC, svfcode commented on cleantalk/lib/Cleantalk/ApbctUni/File/BTree.php
> +						// $myfile = fopen(__DIR__ . "/btree-get-a.txt", "a") or die("Unable to open file!");
Yeah, removed, thanks.

2023-08-30 04:07 UTC, alexandergull approved these changes

2023-08-30 06:19 UTC, Glomberg approved these changes
There is one major note - why the library was implemented by simple copy-paste, but not by composer. Wrong way.

2023-09-07 05:37 UTC, ArtemAnoshin approved these changes

2023-09-11 11:50 UTC, merged